---
title: "Point Patterns"
author: "Luke Ghallahorne"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: yes
    theme: flatly
    code_folding: show
editor_options: 
  markdown: 
    wrap: sentence
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning = FALSE}
library(spatstat)
library(dplyr)
library(ggplot2)
```

```{r}
# Simulated data
n <- 100
patternA <- data.frame(x=rnorm(n),y=rnorm(n),id="A")
patternB <- data.frame(x=runif(n),y=runif(n),id="B")
patternC <- data.frame(expand.grid(x = seq(0, 1, length.out = sqrt(n)),
                                   y = seq(0, 1, length.out = sqrt(n))),
                       id="C")

patternD <- data.frame(expand.grid(x = rep(seq(0, 1, length.out = n/20),2),
                                   y = rep(seq(0, 1, length.out = n/20),2)),
                       id="D")
patternD$x <- jitter(patternD$x)
patternD$y <- jitter(patternD$y)

simDat <- bind_rows(patternA,patternB,patternC,patternD)

simDat <- simDat %>% group_by(id) %>% 
  mutate(x = scales::rescale(x), 
         y=scales::rescale(y))


```


```{r}
patternD <- simDat |> filter(id=="D")


ggplot(patternD, aes(x = x, y = y)) +
  geom_point() + coord_fixed() +
  ggtitle("Pattern D")
```
```{r}
patternD <- ppp(x = patternD$x, y=patternD$y,
                xrange=c(0,1), yrange=c(0,1),
                unitname="km")
summary(patternD)
plot(patternD)
```

```{r}
plot(density(patternD))
points(patternD, pch = 20)
```


```{r}
envK <- envelope(patternD, Kest, nsim = 100, verbose = FALSE)
plot(envK)
```

```{r}
envL <- envelope(patternD, Lest, nsim = 100, verbose = FALSE)
plot(envL)
```

```{r}
ggplot(envK, mapping = aes(x=r, ymin = lo-pi*r^2, ymax=hi-pi*r^2)) +
  geom_ribbon(fill="grey",alpha=0.5) + 
  geom_line(mapping = aes(y=theo-pi*r^2),col="red", linetype="dashed") +
  geom_line(mapping = aes(y=obs-pi*r^2)) +
  labs(y=expression(K(r) - pi~r^2), x = "r") +
  scale_x_continuous(expand = c(0,0))
```

# Sporophores

```{r}
data(sporophores)
summary(sporophores)
```

```{r}
plot(sporophores, chars=c(16,1,2), cex=0.6, leg.args=list(cex=1.1))
points(0,0,pch=16, cex=2)
text(15,8,"Tree", cex=0.75)
```

```{r}
sporo.df <- as.data.frame(sporophores)
plot(density(sporophores))

```


```{r}
sporoK <- envelope(sporophores, Kest, nsim = 100, verbose = FALSE)
plot(sporoK)
```

```{r}
ggplot(sporoK, mapping = aes(x=r, ymin = lo-pi*r^2, ymax=hi-pi*r^2)) +
  geom_ribbon(fill="grey",alpha=0.5) + 
  geom_line(mapping = aes(y=theo-pi*r^2),col="red", linetype="dashed") +
  geom_line(mapping = aes(y=obs-pi*r^2)) +
  labs(y=expression(K(r) - pi~r^2), x = "r") +
  scale_x_continuous(expand = c(0,0))
```



```{r}
# using subset
heb_pub <- subset(sporophores, 
                  marks %in% c("L pubescens","Hebloma spp"), drop=TRUE)
cross_heb_pub <- envelope(heb_pub, "Lcross", verbose=FALSE)
# or directly in envelope (note i and j arguments)
cross_heb_pub <- envelope(sporophores, "Lcross", i="L pubescens", j = "Hebloma spp", verbose=FALSE)
```

```{r}
plot(cross_heb_pub)
```

```{r}
cross_lac_pub <- envelope(sporophores, "Lcross", i="L laccata", j = "L pubescens", verbose=FALSE)
plot(cross_lac_pub)
```

```{r}
cross_heb_lac <- envelope(sporophores, "Lcross", i="L laccata", j = "Hebloma spp", verbose=FALSE)
plot(cross_heb_lac)
```

